#!/bin/bash
# Bash Menu Script Example

# Text Formating
txtgrn=$(tput setaf 2) # Green
txtwht=$(tput setaf 7) # White
txtblu=$(tput setaf 4) # Blue
txtrst=$(tput sgr0) # Text reset.
txtbold=$(tput bold) # Text Bold
txtred=$(tput setaf 1) # red
txtyellow=$(tput setaf 3) # yellow

TXT_START="$txtblu[START]$txtrst";
TXT_FINISH="${txtyellow}FINISHED${txtrst}";
TXT_ERROR="${txtred}ERROR OCCURRED:${txtrst}";

# project specific settings
PROJ_NAME=''
PROJ_PATH=''

DEPLOYMENT_FULL_PATH=''
BUILD_COMMAND=''
RUN_COMMAND=''
HOST_NAME=''
RC_NAME=''

#Handle error status
function error_exit
{
 echo "$TXT_ERROR$1$txtrst" | 1>&2
 exit 1
}

function main() {
    error_exit "Not a valid project:(" 
}

main